/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IRoninVRFCoordinator } from './IRoninVRFCoordinator.js';
export type { WorldCupAxie } from './WorldCupAxie.js';
export * as factories from './factories/index.js';
export { IRoninVRFCoordinator__factory } from './factories/IRoninVRFCoordinator__factory.js';
export { WorldCupAxie__factory } from './factories/WorldCupAxie__factory.js';