/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface IRoninVRFCoordinatorInterface extends Interface {
    getFunction(nameOrSignature: "estimateRequestRandomFee" | "requestRandomSeed"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'estimateRequestRandomFee', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'requestRandomSeed', values: [BigNumberish, BigNumberish, AddressLike, AddressLike]): string;

    decodeFunctionResult(functionFragment: 'estimateRequestRandomFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'requestRandomSeed', data: BytesLike): Result;
  }

  

  export interface IRoninVRFCoordinator extends BaseContract {
    
    connect(runner?: ContractRunner | null): IRoninVRFCoordinator;
    waitForDeployment(): Promise<this>;

    interface: IRoninVRFCoordinatorInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    estimateRequestRandomFee: TypedContractMethod<
      [callbackGasLimit: BigNumberish, gasPrice: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    requestRandomSeed: TypedContractMethod<
      [callbackGasLimit: BigNumberish, gasPrice: BigNumberish, consumer: AddressLike, refundAddress: AddressLike, ],
      [string],
      'payable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'estimateRequestRandomFee'): TypedContractMethod<
      [callbackGasLimit: BigNumberish, gasPrice: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'requestRandomSeed'): TypedContractMethod<
      [callbackGasLimit: BigNumberish, gasPrice: BigNumberish, consumer: AddressLike, refundAddress: AddressLike, ],
      [string],
      'payable'
    >;

    

    filters: {
      
    };
  }