/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface WorldCupAxieInterface extends Interface {
    getFunction(nameOrSignature: "COUNTRY_COUNT" | "axieContract" | "balanceOf" | "balanceOfBatch" | "estimateVRFFee" | "gasPrice" | "isApprovedForAll" | "mintEnd" | "mintStart" | "name" | "onERC721Received" | "owner" | "pendingMints" | "rawFulfillRandomSeed" | "releaseAddress" | "renounceOwnership" | "safeBatchTransferFrom" | "safeTransferFrom" | "setApprovalForAll" | "setCollectionInfo" | "setMintWindow" | "setReleaseAddress" | "setURI" | "setVrfConfig" | "supportsInterface" | "symbol" | "transferOwnership" | "uri" | "vrfCallbackGasLimit" | "vrfCoordinator"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ApprovalForAll" | "AxieReceived" | "CollectionInfoUpdated" | "CountryMinted" | "MintWindowUpdated" | "OwnershipTransferred" | "ReleaseAddressUpdated" | "TransferBatch" | "TransferSingle" | "URI" | "VrfConfigUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'COUNTRY_COUNT', values?: undefined): string;
encodeFunctionData(functionFragment: 'axieContract', values?: undefined): string;
encodeFunctionData(functionFragment: 'balanceOf', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'balanceOfBatch', values: [AddressLike[], BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'estimateVRFFee', values?: undefined): string;
encodeFunctionData(functionFragment: 'gasPrice', values?: undefined): string;
encodeFunctionData(functionFragment: 'isApprovedForAll', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'mintEnd', values?: undefined): string;
encodeFunctionData(functionFragment: 'mintStart', values?: undefined): string;
encodeFunctionData(functionFragment: 'name', values?: undefined): string;
encodeFunctionData(functionFragment: 'onERC721Received', values: [AddressLike, AddressLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'pendingMints', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'rawFulfillRandomSeed', values: [BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'releaseAddress', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'safeBatchTransferFrom', values: [AddressLike, AddressLike, BigNumberish[], BigNumberish[], BytesLike]): string;
encodeFunctionData(functionFragment: 'safeTransferFrom', values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'setApprovalForAll', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'setCollectionInfo', values: [string, string]): string;
encodeFunctionData(functionFragment: 'setMintWindow', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setReleaseAddress', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setURI', values: [string]): string;
encodeFunctionData(functionFragment: 'setVrfConfig', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'symbol', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'uri', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'vrfCallbackGasLimit', values?: undefined): string;
encodeFunctionData(functionFragment: 'vrfCoordinator', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'COUNTRY_COUNT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'axieContract', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'balanceOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'balanceOfBatch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'estimateVRFFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'gasPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isApprovedForAll', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mintEnd', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mintStart', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'name', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'onERC721Received', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pendingMints', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rawFulfillRandomSeed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'releaseAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'safeBatchTransferFrom', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'safeTransferFrom', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setApprovalForAll', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setCollectionInfo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMintWindow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setReleaseAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setURI', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setVrfConfig', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'symbol', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'uri', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vrfCallbackGasLimit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vrfCoordinator', data: BytesLike): Result;
  }

  
    export namespace ApprovalForAllEvent {
      export type InputTuple = [account: AddressLike, operator: AddressLike, approved: boolean];
      export type OutputTuple = [account: string, operator: string, approved: boolean];
      export interface OutputObject {account: string, operator: string, approved: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AxieReceivedEvent {
      export type InputTuple = [minter: AddressLike, axieTokenId: BigNumberish, reqHash: BytesLike];
      export type OutputTuple = [minter: string, axieTokenId: bigint, reqHash: string];
      export interface OutputObject {minter: string, axieTokenId: bigint, reqHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CollectionInfoUpdatedEvent {
      export type InputTuple = [name: string, symbol: string];
      export type OutputTuple = [name: string, symbol: string];
      export interface OutputObject {name: string, symbol: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CountryMintedEvent {
      export type InputTuple = [minter: AddressLike, countryId: BigNumberish, axieTokenId: BigNumberish, reqHash: BytesLike];
      export type OutputTuple = [minter: string, countryId: bigint, axieTokenId: bigint, reqHash: string];
      export interface OutputObject {minter: string, countryId: bigint, axieTokenId: bigint, reqHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MintWindowUpdatedEvent {
      export type InputTuple = [start: BigNumberish, end: BigNumberish];
      export type OutputTuple = [start: bigint, end: bigint];
      export interface OutputObject {start: bigint, end: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ReleaseAddressUpdatedEvent {
      export type InputTuple = [oldAddress: AddressLike, newAddress: AddressLike];
      export type OutputTuple = [oldAddress: string, newAddress: string];
      export interface OutputObject {oldAddress: string, newAddress: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferBatchEvent {
      export type InputTuple = [operator: AddressLike, from: AddressLike, to: AddressLike, ids: BigNumberish[], values: BigNumberish[]];
      export type OutputTuple = [operator: string, from: string, to: string, ids: bigint[], values: bigint[]];
      export interface OutputObject {operator: string, from: string, to: string, ids: bigint[], values: bigint[] };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferSingleEvent {
      export type InputTuple = [operator: AddressLike, from: AddressLike, to: AddressLike, id: BigNumberish, value: BigNumberish];
      export type OutputTuple = [operator: string, from: string, to: string, id: bigint, value: bigint];
      export interface OutputObject {operator: string, from: string, to: string, id: bigint, value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace URIEvent {
      export type InputTuple = [value: string, id: BigNumberish];
      export type OutputTuple = [value: string, id: bigint];
      export interface OutputObject {value: string, id: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VrfConfigUpdatedEvent {
      export type InputTuple = [coordinator: AddressLike, callbackGasLimit: BigNumberish];
      export type OutputTuple = [coordinator: string, callbackGasLimit: bigint];
      export interface OutputObject {coordinator: string, callbackGasLimit: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface WorldCupAxie extends BaseContract {
    
    connect(runner?: ContractRunner | null): WorldCupAxie;
    waitForDeployment(): Promise<this>;

    interface: WorldCupAxieInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    COUNTRY_COUNT: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    axieContract: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    balanceOf: TypedContractMethod<
      [account: AddressLike, id: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    balanceOfBatch: TypedContractMethod<
      [accounts: AddressLike[], ids: BigNumberish[], ],
      [bigint[]],
      'view'
    >
    

    
    estimateVRFFee: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    gasPrice: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    isApprovedForAll: TypedContractMethod<
      [account: AddressLike, operator: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    mintEnd: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    mintStart: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    name: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    onERC721Received: TypedContractMethod<
      [arg0: AddressLike, from: AddressLike, tokenId: BigNumberish, arg3: BytesLike, ],
      [string],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pendingMints: TypedContractMethod<
      [reqHash: BytesLike, ],
      [[string, bigint] & {minter: string, axieTokenId: bigint }],
      'view'
    >
    

    
    rawFulfillRandomSeed: TypedContractMethod<
      [reqHash: BytesLike, randomSeed: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    releaseAddress: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    safeBatchTransferFrom: TypedContractMethod<
      [from: AddressLike, to: AddressLike, ids: BigNumberish[], values: BigNumberish[], data: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    safeTransferFrom: TypedContractMethod<
      [from: AddressLike, to: AddressLike, id: BigNumberish, value: BigNumberish, data: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    setApprovalForAll: TypedContractMethod<
      [operator: AddressLike, approved: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setCollectionInfo: TypedContractMethod<
      [newName: string, newSymbol: string, ],
      [void],
      'nonpayable'
    >
    

    
    setMintWindow: TypedContractMethod<
      [start: BigNumberish, end: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setReleaseAddress: TypedContractMethod<
      [newReleaseAddress: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setURI: TypedContractMethod<
      [newuri: string, ],
      [void],
      'nonpayable'
    >
    

    
    setVrfConfig: TypedContractMethod<
      [coordinator: AddressLike, callbackGasLimit: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    symbol: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    uri: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    vrfCallbackGasLimit: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    vrfCoordinator: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'COUNTRY_COUNT'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'axieContract'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'balanceOf'): TypedContractMethod<
      [account: AddressLike, id: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'balanceOfBatch'): TypedContractMethod<
      [accounts: AddressLike[], ids: BigNumberish[], ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'estimateVRFFee'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'gasPrice'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'isApprovedForAll'): TypedContractMethod<
      [account: AddressLike, operator: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'mintEnd'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'mintStart'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'name'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'onERC721Received'): TypedContractMethod<
      [arg0: AddressLike, from: AddressLike, tokenId: BigNumberish, arg3: BytesLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pendingMints'): TypedContractMethod<
      [reqHash: BytesLike, ],
      [[string, bigint] & {minter: string, axieTokenId: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'rawFulfillRandomSeed'): TypedContractMethod<
      [reqHash: BytesLike, randomSeed: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'releaseAddress'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'safeBatchTransferFrom'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, ids: BigNumberish[], values: BigNumberish[], data: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'safeTransferFrom'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, id: BigNumberish, value: BigNumberish, data: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setApprovalForAll'): TypedContractMethod<
      [operator: AddressLike, approved: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setCollectionInfo'): TypedContractMethod<
      [newName: string, newSymbol: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setMintWindow'): TypedContractMethod<
      [start: BigNumberish, end: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setReleaseAddress'): TypedContractMethod<
      [newReleaseAddress: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setURI'): TypedContractMethod<
      [newuri: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setVrfConfig'): TypedContractMethod<
      [coordinator: AddressLike, callbackGasLimit: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'symbol'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'uri'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'vrfCallbackGasLimit'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'vrfCoordinator'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'ApprovalForAll'): TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
getEvent(key: 'AxieReceived'): TypedContractEvent<AxieReceivedEvent.InputTuple, AxieReceivedEvent.OutputTuple, AxieReceivedEvent.OutputObject>;
getEvent(key: 'CollectionInfoUpdated'): TypedContractEvent<CollectionInfoUpdatedEvent.InputTuple, CollectionInfoUpdatedEvent.OutputTuple, CollectionInfoUpdatedEvent.OutputObject>;
getEvent(key: 'CountryMinted'): TypedContractEvent<CountryMintedEvent.InputTuple, CountryMintedEvent.OutputTuple, CountryMintedEvent.OutputObject>;
getEvent(key: 'MintWindowUpdated'): TypedContractEvent<MintWindowUpdatedEvent.InputTuple, MintWindowUpdatedEvent.OutputTuple, MintWindowUpdatedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'ReleaseAddressUpdated'): TypedContractEvent<ReleaseAddressUpdatedEvent.InputTuple, ReleaseAddressUpdatedEvent.OutputTuple, ReleaseAddressUpdatedEvent.OutputObject>;
getEvent(key: 'TransferBatch'): TypedContractEvent<TransferBatchEvent.InputTuple, TransferBatchEvent.OutputTuple, TransferBatchEvent.OutputObject>;
getEvent(key: 'TransferSingle'): TypedContractEvent<TransferSingleEvent.InputTuple, TransferSingleEvent.OutputTuple, TransferSingleEvent.OutputObject>;
getEvent(key: 'URI'): TypedContractEvent<URIEvent.InputTuple, URIEvent.OutputTuple, URIEvent.OutputObject>;
getEvent(key: 'VrfConfigUpdated'): TypedContractEvent<VrfConfigUpdatedEvent.InputTuple, VrfConfigUpdatedEvent.OutputTuple, VrfConfigUpdatedEvent.OutputObject>;

    filters: {
      
      'ApprovalForAll(address,address,bool)': TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
      ApprovalForAll: TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
    

      'AxieReceived(address,uint256,bytes32)': TypedContractEvent<AxieReceivedEvent.InputTuple, AxieReceivedEvent.OutputTuple, AxieReceivedEvent.OutputObject>;
      AxieReceived: TypedContractEvent<AxieReceivedEvent.InputTuple, AxieReceivedEvent.OutputTuple, AxieReceivedEvent.OutputObject>;
    

      'CollectionInfoUpdated(string,string)': TypedContractEvent<CollectionInfoUpdatedEvent.InputTuple, CollectionInfoUpdatedEvent.OutputTuple, CollectionInfoUpdatedEvent.OutputObject>;
      CollectionInfoUpdated: TypedContractEvent<CollectionInfoUpdatedEvent.InputTuple, CollectionInfoUpdatedEvent.OutputTuple, CollectionInfoUpdatedEvent.OutputObject>;
    

      'CountryMinted(address,uint256,uint256,bytes32)': TypedContractEvent<CountryMintedEvent.InputTuple, CountryMintedEvent.OutputTuple, CountryMintedEvent.OutputObject>;
      CountryMinted: TypedContractEvent<CountryMintedEvent.InputTuple, CountryMintedEvent.OutputTuple, CountryMintedEvent.OutputObject>;
    

      'MintWindowUpdated(uint64,uint64)': TypedContractEvent<MintWindowUpdatedEvent.InputTuple, MintWindowUpdatedEvent.OutputTuple, MintWindowUpdatedEvent.OutputObject>;
      MintWindowUpdated: TypedContractEvent<MintWindowUpdatedEvent.InputTuple, MintWindowUpdatedEvent.OutputTuple, MintWindowUpdatedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'ReleaseAddressUpdated(address,address)': TypedContractEvent<ReleaseAddressUpdatedEvent.InputTuple, ReleaseAddressUpdatedEvent.OutputTuple, ReleaseAddressUpdatedEvent.OutputObject>;
      ReleaseAddressUpdated: TypedContractEvent<ReleaseAddressUpdatedEvent.InputTuple, ReleaseAddressUpdatedEvent.OutputTuple, ReleaseAddressUpdatedEvent.OutputObject>;
    

      'TransferBatch(address,address,address,uint256[],uint256[])': TypedContractEvent<TransferBatchEvent.InputTuple, TransferBatchEvent.OutputTuple, TransferBatchEvent.OutputObject>;
      TransferBatch: TypedContractEvent<TransferBatchEvent.InputTuple, TransferBatchEvent.OutputTuple, TransferBatchEvent.OutputObject>;
    

      'TransferSingle(address,address,address,uint256,uint256)': TypedContractEvent<TransferSingleEvent.InputTuple, TransferSingleEvent.OutputTuple, TransferSingleEvent.OutputObject>;
      TransferSingle: TypedContractEvent<TransferSingleEvent.InputTuple, TransferSingleEvent.OutputTuple, TransferSingleEvent.OutputObject>;
    

      'URI(string,uint256)': TypedContractEvent<URIEvent.InputTuple, URIEvent.OutputTuple, URIEvent.OutputObject>;
      URI: TypedContractEvent<URIEvent.InputTuple, URIEvent.OutputTuple, URIEvent.OutputObject>;
    

      'VrfConfigUpdated(address,uint32)': TypedContractEvent<VrfConfigUpdatedEvent.InputTuple, VrfConfigUpdatedEvent.OutputTuple, VrfConfigUpdatedEvent.OutputObject>;
      VrfConfigUpdated: TypedContractEvent<VrfConfigUpdatedEvent.InputTuple, VrfConfigUpdatedEvent.OutputTuple, VrfConfigUpdatedEvent.OutputObject>;
    
    };
  }