/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IRoninVRFCoordinator__factory } from './IRoninVRFCoordinator__factory.js';
export { WorldCupAxie__factory } from './WorldCupAxie__factory.js';