/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IRoninVRFCoordinator, IRoninVRFCoordinatorInterface } from "../IRoninVRFCoordinator.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "callbackGasLimit",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "gasPrice",
        "type": "uint256"
      }
    ],
    "name": "estimateRequestRandomFee",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "callbackGasLimit",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "gasPrice",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "consumer",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "refundAddress",
        "type": "address"
      }
    ],
    "name": "requestRandomSeed",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "reqHash",
        "type": "bytes32"
      }
    ],
    "stateMutability": "payable",
    "type": "function"
  }
] as const;

  export class IRoninVRFCoordinator__factory {
    static readonly abi = _abi;
    static createInterface(): IRoninVRFCoordinatorInterface {
      return new Interface(_abi) as IRoninVRFCoordinatorInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IRoninVRFCoordinator {
      return new Contract(address, _abi, runner) as unknown as IRoninVRFCoordinator;
    }
  }
  