export const countries = [
  "Algeria",
  "Argentina",
  "Australia",
  "Austria",
  "Belgium",
  "Bosnia and Herzegovina",
  "Brazil",
  "Cabo Verde",
  "Canada",
  "Colombia",
  "Congo DR",
  "Côte d'Ivoire",
  "Croatia",
  "Curaçao",
  "Czechia",
  "Ecuador",
  "Egypt",
  "England",
  "France",
  "Germany",
  "Ghana",
  "Haiti",
  "Iran",
  "Iraq",
  "Japan",
  "Jordan",
  "South Korea",
  "Mexico",
  "Morocco",
  "Netherlands",
  "New Zealand",
  "Norway",
  "Panama",
  "Paraguay",
  "Portugal",
  "Qatar",
  "Saudi Arabia",
  "Scotland",
  "Senegal",
  "South Africa",
  "Spain",
  "Sweden",
  "Switzerland",
  "Tunisia",
  "Türkiye",
  "United States",
  "Uruguay",
  "Uzbekistan"
] as const;

export function imageUrl(tokenId: number) {
  const base = "/images";
  return `${base.replace(/\/$/, "")}/${tokenId}.png`;
}
